export const listNav = [
  {
    name: "Store",
    listItem: [
      {
        listName: "Featured",
        listIems: [
          "Mac",
          "iPad",
          "iPhone",
          "Watch",
          "AirPods",
          "TV & Home",
          "Accessories",
          "Vision Pro",
          "Beats",
          "HomeKit Devices",
          "Apple Gift Guide",
          "iPod touch",
          "Apple Displays",
        ],
      },
      {
        listName: "Quick Links",
        listIems: [
          "Find a Store",
          "Order Status",
          "Apple Trade In",
          "Gift Cards",
          "Financing",
          "Shop with Specialist",
          "Track Your Order",
          "Personal Setup",
          "Store App",
          "Online Chat",
          "Gift Finder",
        ],
      },
      {
        listName: "Deals",
        listIems: [
          "Education Store",
          "Refurbished",
          "Business Store",
          "Limited-Time Offers",
          "Veterans and Military",
          "Certified Pre-Owned",
          "Seasonal Promotions",
          "Bundle Offers",
          "Student Discounts",
          "Trade-In Deals",
        ],
      },
      {
        listName: "Services",
        listIems: [
          "Financing",
          "Gift Cards",
          "AppleCare+",
          "Apple One",
          "Today at Apple",
          "Apple Pay",
          "iCloud+",
          "Apple Card",
          "Apple Wallet",
          "Apple Cash",
          "Subscription Plans",
        ],
      },
      {
        listName: "Programs",
        listIems: [
          "Recycling",
          "Upgrade Program",
          "Free Personal Session",
          "Apple Developer",
          "Apple for Kids",
          "Trade-In Program",
          "Apple GiveBack",
          "Student Discounts",
          "Apple for Business",
          "Eco Initiatives",
        ],
      },
    ],
  },
  {
    name: "Mac",
    listItem: [
      {
        listName: "Mac Models",
        listIems: [
          "MacBook Air",
          "MacBook Pro",
          "iMac",
          "Mac mini",
          "Mac Studio",
          "Mac Pro",
          "MacBook Air M3",
          "iMac Pro",
          "MacBook Pro M4",
          "Mac mini M3",
          "Mac Studio Ultra",
        ],
      },
      {
        listName: "Compare",
        listIems: [
          "Compare All Models",
          "Why Mac",
          "macOS Sonoma",
          "Performance Benchmarks",
          "Apple Silicon",
          "Battery Life",
          "Display Options",
          "Storage Configurations",
          "Graphics Performance",
          "Thermal Efficiency",
        ],
      },
      {
        listName: "Accessories",
        listIems: [
          "Displays",
          "Keyboards",
          "Mice",
          "Trackpads",
          "Adapters",
          "Hubs",
          "Magic Accessories",
          "External Storage",
          "Docking Stations",
          "Protective Cases",
          "Cooling Pads",
          "USB-C Cables",
        ],
      },
      {
        listName: "For Work & Study",
        listIems: [
          "Mac for Business",
          "Mac for Education",
          "Coding on Mac",
          "Creative Workflows",
          "Scientific Research",
          "Video Production",
          "Graphic Design",
          "Music Creation",
          "Data Analysis",
          "3D Rendering",
        ],
      },
      {
        listName: "AppleCare+ & Support",
        listIems: [
          "AppleCare+",
          "Setup & Learning",
          "Service & Repair",
          "Software Updates",
          "Mac Community",
          "Tutorials",
          "Diagnostics",
          "Extended Warranty",
          "Remote Support",
          "Hardware Upgrades",
        ],
      },
    ],
  },
  {
    name: "iPad",
    listItem: [
      {
        listName: "iPad Models",
        listIems: [
          "iPad Pro",
          "iPad Air",
          "iPad",
          "iPad mini",
          "iPad Pro M4",
          "iPad 10th Gen",
          "iPad Air M2",
          "iPad mini 7",
          "iPad Pro 13-inch",
          "iPad 11th Gen",
        ],
      },
      {
        listName: "Compare",
        listIems: [
          "Compare All iPads",
          "Why iPad",
          "iPadOS 17",
          "App Store",
          "Apple Pencil Pro",
          "Performance Specs",
          "Display Technology",
          "Battery Comparison",
          "Storage Options",
          "Connectivity Features",
        ],
      },
      {
        listName: "Accessories",
        listIems: [
          "Apple Pencil",
          "Magic Keyboard",
          "Smart Folio",
          "Chargers",
          "Screen Protectors",
          "Keyboard Covers",
          "Stylus Cases",
          "USB-C Hubs",
          "Protective Sleeves",
          "Carrying Bags",
          "Audio Adapters",
        ],
      },
      {
        listName: "Use Cases",
        listIems: [
          "Drawing",
          "Note-Taking",
          "Gaming",
          "School",
          "Video Editing",
          "Music Production",
          "AR Experiences",
          "Reading eBooks",
          "Digital Art",
          "Presentation Design",
          "Remote Learning",
        ],
      },
      {
        listName: "AppleCare+ & Support",
        listIems: [
          "AppleCare+",
          "Setup Help",
          "Repairs",
          "User Guides",
          "iPad Community",
          "Software Tips",
          "Troubleshooting",
          "Warranty Options",
          "Remote Diagnostics",
          "App Support",
        ],
      },
    ],
  },
  {
    name: "iPhone",
    listItem: [
      {
        listName: "iPhone Models",
        listIems: [
          "iPhone 15 Pro",
          "iPhone 15",
          "iPhone 14",
          "iPhone SE",
          "Compare iPhones",
          "iPhone 16",
          "iPhone 16 Pro",
          "iPhone 16 Pro Max",
          "iPhone 15 Plus",
          "iPhone 14 Pro",
          "iPhone SE 4",
        ],
      },
      {
        listName: "Accessories",
        listIems: [
          "MagSafe",
          "Cases",
          "Chargers",
          "Power Banks",
          "Wireless Earbuds",
          "Screen Protectors",
          "Car Mounts",
          "Wallet Cases",
          "Charging Docks",
          "Camera Lenses",
          "Tripods",
        ],
      },
      {
        listName: "Features",
        listIems: [
          "iOS 17",
          "Dynamic Island",
          "A17 Pro Chip",
          "Camera System",
          "Emergency SOS",
          "Apple Intelligence",
          "Satellite Connectivity",
          "ProMotion Display",
          "Action Button",
          "Always-On Display",
          "Cinematic Mode",
        ],
      },
      {
        listName: "Programs",
        listIems: [
          "iPhone Upgrade Program",
          "Switch from Android",
          "Carrier Deals",
          "Installment Plans",
          "Trade-In Program",
          "Apple Card Payments",
          "Student Offers",
          "Business Solutions",
          "Loyalty Program",
          "Family Sharing",
        ],
      },
      {
        listName: "Support",
        listIems: [
          "AppleCare+",
          "Battery Service",
          "Repair Options",
          "Setup Guide",
          "iPhone Community",
          "Diagnostics",
          "Software Updates",
          "Lost Device Support",
          "Security Support",
          "Backup Solutions",
        ],
      },
    ],
  },
  {
    name: "Watch",
    listItem: [
      {
        listName: "Watch Models",
        listIems: [
          "Apple Watch Ultra 2",
          "Series 9",
          "SE",
          "Apple Watch Nike",
          "Apple Watch Hermès",
          "Apple Watch Ultra 3",
          "Series 10",
          "Apple Watch SE 3",
          "Apple Watch Edition",
        ],
      },
      {
        listName: "Bands",
        listIems: [
          "Sport Band",
          "Milanese Loop",
          "Leather Bands",
          "Nike Bands",
          "Hermès Bands",
          "Woven Nylon",
          "Metal Mesh",
          "Solo Loop",
          "Braided Solo Loop",
          "Sport Loop",
          "Ocean Band",
        ],
      },
      {
        listName: "Features",
        listIems: [
          "Heart Rate",
          "ECG",
          "Fitness Tracking",
          "Sleep",
          "Blood Oxygen",
          "Fall Detection",
          "Crash Detection",
          "Temperature Sensing",
          "Cycle Tracking",
          "Stress Monitoring",
          "Hydration Tracking",
        ],
      },
      {
        listName: "Compare",
        listIems: [
          "Compare Watches",
          "watchOS 10",
          "Why Apple Watch",
          "Health Insights",
          "Customization Options",
          "Battery Life",
          "Connectivity Options",
          "Water Resistance",
          "Display Comparison",
        ],
      },
      {
        listName: "Support",
        listIems: [
          "AppleCare+",
          "Service & Repair",
          "Setup Guide",
          "Tips & Tricks",
          "Watch Community",
          "Software Updates",
          "Warranty Info",
          "Health App Support",
          "Remote Diagnostics",
          "Band Compatibility",
        ],
      },
    ],
  },
  {
    name: "Vision",
    listItem: [
      {
        listName: "Vision Pro",
        listIems: [
          "Overview",
          "Tech Specs",
          "Design",
          "Apps",
          "Demos",
          "Developer Tools",
          "Accessories",
          "Custom Fit Options",
          "Vision Pro Lite",
          "Vision Pro Enterprise",
          "Demo Sessions",
        ],
      },
      {
        listName: "Features",
        listIems: [
          "Eye Tracking",
          "Spatial Audio",
          "Hand Gestures",
          "Passthrough",
          "3D Capture",
          "Immersive Displays",
          "Gesture Control",
          "Spatial Video",
          "Environment Customization",
          "Voice Control",
          "Multi-User Support",
        ],
      },
      {
        listName: "Use Cases",
        listIems: [
          "Productivity",
          "Movies & Games",
          "FaceTime",
          "Multitasking",
          "Immersive Work",
          "Virtual Collaboration",
          "AR Design",
          "Virtual Training",
          "3D Modeling",
          "Medical Visualization",
          "Gaming Immersion",
        ],
      },
    ],
  },
  {
    name: "AirPods",
    listItem: [
      {
        listName: "AirPods Models",
        listIems: [
          "AirPods Pro",
          "AirPods 3rd Gen",
          "AirPods 2nd Gen",
          "AirPods Max",
          "AirPods Pro 2",
          "AirPods 4",
          "AirPods Lite",
          "AirPods Max 2",
          "Beats Fit Pro",
        ],
      },
      {
        listName: "Accessories",
        listIems: [
          "Charging Cases",
          "Ear Tips",
          "Cables",
          "Cases",
          "Wireless Charging Mat",
          "Protective Skins",
          "Carrying Clips",
          "Custom Engravings",
          "Lanyards",
          "Cleaning Tools",
        ],
      },
      {
        listName: "Audio Features",
        listIems: [
          "Spatial Audio",
          "Active Noise Cancellation",
          "Adaptive Transparency",
          "Find My Support",
          "Conversation Boost",
          "Personalized Audio",
          "Lossless Audio",
          "Adaptive EQ",
          "Dynamic Head Tracking",
          "Voice Isolation",
        ],
      },
    ],
  },
  {
    name: "TV & Home",
    listItem: [
      {
        listName: "Devices",
        listIems: [
          "Apple TV 4K",
          "HomePod",
          "HomePod mini",
          "Apple TV HD",
          "HomePod 2",
          "HomePod Pro",
          "Smart Displays",
          "HomeKit Sensors",
          "Apple TV 8K",
        ],
      },
      {
        listName: "Smart Home",
        listIems: [
          "Home App",
          "HomeKit",
          "Matter",
          "Siri Shortcuts",
          "Automations",
          "Thread Networking",
          "Security Cameras",
          "Smart Locks",
          "Thermostats",
          "Smart Lights",
          "Motion Sensors",
        ],
      },
      {
        listName: "Entertainment",
        listIems: [
          "Apple TV+",
          "Apple Music",
          "Fitness+",
          "Arcade",
          "Podcasts",
          "Home Theater",
          "Live TV",
          "Music Videos",
          "Kids Content",
          "Live Concerts",
          "Sports Streaming",
        ],
      },
    ],
  },
  {
    name: "Entertainment",
    listItem: [
      {
        listName: "Services",
        listIems: [
          "Apple TV+",
          "Apple Music",
          "Apple Arcade",
          "Fitness+",
          "News+",
          "Books",
          "Apple Podcasts+",
          "iCloud+",
          "Apple Fitness Studio",
          "Apple News Audio",
          "Apple Music Classical",
          "Apple Books+",
        ],
      },
      {
        listName: "Watch & Listen",
        listIems: [
          "TV Shows",
          "Movies",
          "Podcasts",
          "Live Sports",
          "Concerts",
          "Music Videos",
          "Audiobooks",
          "Short Films",
          "Live Radio",
          "Behind-the-Scenes",
          "Trailers",
        ],
      },
      {
        listName: "Content",
        listIems: [
          "Kids & Family",
          "Originals",
          "Documentaries",
          "Comedy",
          "Drama Series",
          "Sci-Fi & Fantasy",
          "Reality TV",
          "Thrillers",
          "Action & Adventure",
          "Anime",
          "Award-Winning Films",
        ],
      },
    ],
  },
  {
    name: "Accessories",
    listItem: [
      {
        listName: "By Device",
        listIems: [
          "Mac",
          "iPhone",
          "iPad",
          "Watch",
          "AirPods",
          "Vision Pro",
          "Apple TV",
          "HomePod",
          "Beats",
          "iPod touch",
          "Mac Studio",
          "HomeKit Devices",
        ],
      },
      {
        listName: "Categories",
        listIems: [
          "Chargers",
          "Cases",
          "Cables",
          "Adapters",
          "Mounts",
          "Cleaning Kits",
          "Stands",
          "Docks",
          "Audio Adapters",
          "Storage Solutions",
          "Screen Cleaners",
          "Travel Adapters",
        ],
      },
      {
        listName: "Featured",
        listIems: [
          "Best Sellers",
          "New Arrivals",
          "Apple Certified",
          "Limited Editions",
          "Eco-Friendly",
          "Custom Engravings",
          "Seasonal Collections",
          "Partner Brands",
          "Luxury Accessories",
          "Tech Gadgets",
        ],
      },
    ],
  },
  {
    name: "Support",
    listItem: [
      {
        listName: "Help Topics",
        listIems: [
          "iPhone",
          "Mac",
          "iPad",
          "Apple ID",
          "Billing & Subscriptions",
          "iCloud",
          "Privacy Settings",
          "Accessibility",
          "Security Features",
          "Family Sharing",
          "App Store Support",
          "Device Setup",
        ],
      },
      {
        listName: "Repair & Warranty",
        listIems: [
          "Check Coverage",
          "Service Options",
          "AppleCare+",
          "Repair Pricing",
          "Express Replacement",
          "Battery Replacement",
          "Screen Repair",
          "Trade-In Support",
          "Warranty Extensions",
          "Accidental Damage",
        ],
      },
      {
        listName: "Contact",
        listIems: [
          "Chat Support",
          "Call Support",
          "Find a Store",
          "Email Us",
          "Genius Bar",
          "Schedule Appointment",
          "Virtual Consultations",
          "Feedback Form",
          "Social Media Support",
          "Priority Support",
        ],
      },
      {
        listName: "Resources",
        listIems: [
          "User Guides",
          "Community",
          "Accessibility Support",
          "System Status",
          "Tutorials & Videos",
          "FAQ",
          "Product Manuals",
          "Software Downloads",
          "Troubleshooting Guides",
          "Support App",
        ],
      },
    ],
  },
];